### ISSUE TITLE
Installing from source on Windows 10 64-bit fails

### ISSUE THREAD

**Issue by naikymen** [ropensci/ijtiff#11]
Hi! I wanted to reuse the `src/makefile.win` and `tools/winlibs.R` in my package, but ran into a problem testing `ijtiff` itself.

```r
install.packages("ijtiff", type = "source")
```
Using that command in Windows 10 64-bit, installation of `ijtiff` fails with missing file errors, like `tiffio.h` (i can post a full error log if it'd help).

Is this expected? The binary version installs perfectly fine.

Thanks!

**Comment by naikymen** [comment]
The problem was related to `Makevars.win`. The "if" confition there was not met in Windows even though it was 64 bit.

```
ifeq "$(WIN)" "64"
PKG_CPPFLAGS= -I../windows/libtiff-4.0.9/include
PKG_LIBS= -L../windows/libtiff-4.0.9/lib${R_ARCH} -ltiff -ljpeg -llzma -lz
else
PKG_LIBS= -ltiff -ljpeg -llzma -lz
endif

# more stuff ...
```

I commented out the if, and everything worked. Finally.


```
# ifeq "$(WIN)" "64"
PKG_CPPFLAGS= -I../windows/libtiff-4.0.9/include
PKG_LIBS= -L../windows/libtiff-4.0.9/lib${R_ARCH} -ltiff -ljpeg -llzma -lz
# else
# PKG_LIBS= -ltiff -ljpeg -llzma -lz
# endif

# more stuff ...
```

Feel free to close this! thanks for the code :)

**Comment by rorynolan** [comment]
Hi @naikymen thanks for the comments. It's strange that you need to comment out that line. In [Writing R Extensions]() it says 

> Environment or make variables can be used to select different macros for 32- and 64-bit code, for example (GNU make syntax, allowed on Windows)
```
ifeq "$(WIN)" "64"
PKG_LIBS = value for 64-bit Windows
else
PKG_LIBS = value for 32-bit Windows
endif
```
so it should work. However these environment variables only get set during calls to `R CMD INSTALL`. If you try to compile the code otherwise, this and other environment variables will not be set. Does this help? If you want to distribute your package eventually, you'll need to figure this out.

**Comment by naikymen** [comment]
Strange indeed. I'll try to figure out what is going on later, and post the results.

Thank you :)

**Comment by jeroen** [comment]
@rorynolan your package also doesn't build on our cran-like server: https://github.com/r-universe/ropensci/actions/runs/184771182

The problem is that 64-windows installations need to compile both 32-bit and 64-bit windows. You are disabling this in your appveyor config by building with `--no-multiarch` but that is not a general solution.

**Comment by rorynolan** [comment]
@jeroen I did all of this because on CRAN the build check on 32bit Win was crashing without producing an error that I could debug. Couldn't track the error down. The same is still happening to Simon Urbanek's tiff package https://www.r-project.org/nosvn/R.check/r-release-windows-ix86+x86_64/tiff-00check.html. During example running, the build check crashes, which is exactly what was happening to me.

**Comment by rorynolan** [comment]
@jeroen I made your changes and tried again on AppVeyor. The old error returns (a runtime crash). I can avoid it by skipping all examples and tests (compilation is fine) but I feel that this is not a good solution. 
The failed AppVeyor build can be found at https://ci.appveyor.com/project/rorynolan/ijtiff-62f4g.

**Comment by jeroen** [comment]
Right, the problem is that CRAN has some very old version of libtiff installed on their server, that sadly they don't want to remove.

I had prepared a branch for you called `winlibs` that should solve the issue, but I am still waiting for the winbuilder results.

**Comment by rorynolan** [comment]
I copied your winlibs branch changes into master (not great git management I know) and did a push. It fails on AppVeyor just like it fails on CRAN. https://ci.appveyor.com/project/rorynolan/ijtiff-62f4g

**Comment by jeroen** [comment]
Ah I hadn't realized you had disabled examples for 32-bit. I'll have another look then. It could be you have an actual 32-bit bug somewhere.

**Comment by rorynolan** [comment]
That is very possible. I lifted a lot of code from Urbanek's tiff package and clearly inherited the error from there. I spent days trying to find it but eventually I gave up and opted for basically just not working on 32 bit windows. The curious thing is it works on CRAN solaris which I believe is 32 bit.

**Comment by jeroen** [comment]
This is what my debugger says:

```
AddrPC   Params
6F144D58 000000C8 00650073 0FB16E48  ijtiff.dll!read_tif_C  [C:/Users/jeroen/Documents/ijtiff/src/read.c @ 307]
   305:         const uint8_t *v = (const uint8_t*) buf + i;
   306:         if (bps == 8) {
>  307:           ci = v[0];
   308:         } else if (bps == 16) {
   309:           ci = ((const uint16_t*) v)[0];
```

**Comment by rorynolan** [comment]
OK great thanks I'll look into it. Not sure I'll be able to fix it, but it appears that a call to `_TIFFmalloc()` a few lines above is the problem. That `v[0]` is the first attempt to access that `malloc`ed memory.
Really appreciate your help.

**Comment by jeroen** [comment]
Ahhh I think I found the problem. The headers for 32-bit are different then for 64-bit. Let me try to fix this and send you a pr...
